### ISSUE TITLE
Create readthedocs/sphinx site

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/bartender#13]
The README is becoming large and mixes user and developer docs. 

It would be nice to have a documentation site using Sphinx and hosted on Readthedocs.

Use https://i-vresse-bartender.readthedocs.io/ as https://bartender.readthedocs.io/ is already taken.

README could be split into
* CONTRIBUTING.md
* docs/index.md
* docs/usage.md
* docs/user_management.md
* docs/configuration.md

**Comment by Peter9192** [comment]
Or use GH actions bartender.github.io? Ben recently wrote a nice [blog](https://blog.esciencecenter.nl/versioned-documentation-using-only-github-actions-and-github-pages-1825296e31aa) about versioned docs on GH pages.

**Comment by sverhoeven** [comment]
Add Markdown support with myst see https://github.com/i-VRESSE/bartender/pull/17/files#r1085534781

**Comment by Peter9192** [comment]
To do:
- [ ] move https://github.com/i-VRESSE/bartender#haddock3-example to https://github.com/i-VRESSE/bartended-haddock3 and link to that.
- [ ] TLDR/quickstart will be deployment only, move detailed instructions to developer chapter.
