### ISSUE TITLE
Add markdown linter to CI and/or pre-commit

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/bartender#28]
The Markdown files should be formatted using a style.

Use https://github.com/markdownlint/markdownlint to enforce style.

**Comment by Peter9192** [comment]
or a python alternative: https://github.com/jackdewinter/pymarkdown? Also works with pre-commit: https://github.com/jackdewinter/pymarkdown/blob/main/docs/pre-commit.md

**Comment by Peter9192** [comment]
After trying out a few, I settled on https://github.com/igorshubovych/markdownlint-cli. Arrived there via https://stackoverflow.com/a/74551354. Like the configuration options and the autofix option
