### ISSUE TITLE
Switch to Google style doc strings

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/bartender#36]
The standard sphinx doc strings are a bit verbose. It would be nice to switch to [Google styled docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). 

To implement we should take care that the sphinx-build and linter keep working.

**Comment by Peter9192** [comment]
Perhaps we could use https://github.com/cbillingham/docconvert or a similar tool? I'd be willing to give that a try.

**Comment by Peter9192** [comment]
Tried docconvert and pyment. Both struggle with async definitions. Pyment also seems to struggle with type annotations.

**Comment by Peter9192** [comment]
docconvert now also parses async functions and seems to do a good job
